# batch_size
batch_size: 64
val_batch_size: 64
# batch_size_test: 8
num_workers: 16

# Optimization
AdamW.betas: [0.8, 0.99]
AdamW.lr: 0.0001
ExponentialLR.gamma: 0.999996

amp: false
device: cuda
num_iters: 300000
save_iters: []
# save_iters: [10000, 50000, 100000, 200000]
valid_freq: 10000
sample_freq: 10000
# num_workers: 32
val_idx: [0, 1, 2, 3, 4, 5, 6, 7]
seed: 0
lambdas:
  mel/loss: 15.0
  adv/feat_loss: 2.0
  adv/gen_loss: 1.0
  vq/commitment_loss: 0.25
  vq/codebook_loss: 1.0